version: '3'
services:
  mysql:
    container_name: mysql
    image: "mysql:5.7"
    restart: always
    networks:
      - outside
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'test'
      MYSQL_PASS: 'test'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - "./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf"
      #- "./init:/docker-entrypoint-initdb.d/"
    #  - "./data/mysql:/var/lib/mysql"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535